const fakecourses = [
   
    {
        name: "Aminul",
        email: "abir13719@gmail.com",
        title: "Mastering Conversational English",
        price: 2250,
        oldPrice: 4500,
        status: "approved",
        category: "Language",
        detailsCourse: "Improve real-life English conversation skills with practical examples.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Aminul",
        email: "abir13719@gmail.com",
        title: "Spanish for Beginners",
        price: 2600,
        oldPrice: 5200,
        status: "approved",
        category: "Language",
        detailsCourse: "Learn basic Spanish vocabulary, grammar, and daily conversations.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Maria Lopez",
        email: "maria@mail.com",
        title: "French Basics",
        price: 2400,
        oldPrice: 4800,
        status: "approved",
        category: "Language",
        detailsCourse: "French pronunciation, greetings, and simple sentence formation.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Ali Hasan",
        email: "ali@mail.com",
        title: "Arabic for Beginners",
        price: 2700,
        oldPrice: 5400,
        status: "approved",
        category: "Language",
        detailsCourse: "Learn Arabic letters, words, and basic conversation.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },

    {
        name: "John Doe",
        email: "john@mail.com",
        title: "JavaScript for Beginners",
        price: 3000,
        oldPrice: 6000,
        status: "approved",
        category: "Programming",
        detailsCourse: "Learn JS fundamentals, functions, loops, and DOM.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "John Doe",
        email: "john@mail.com",
        title: "Advanced JavaScript",
        price: 3500,
        oldPrice: 7000,
        status: "approved",
        category: "Programming",
        detailsCourse: "Closures, async JS, promises, and performance optimization.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Sarah Khan",
        email: "sarah@mail.com",
        title: "React for Beginners",
        price: 3200,
        oldPrice: 6400,
        status: "approved",
        category: "Programming",
        detailsCourse: "Build modern UIs with React, hooks, and components.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Sarah Khan",
        email: "sarah@mail.com",
        title: "Node.js & Express",
        price: 3400,
        oldPrice: 6800,
        status: "approved",
        category: "Programming",
        detailsCourse: "Backend development using Node.js, Express, and REST APIs.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Mike Ross",
        email: "mike@mail.com",
        title: "MongoDB Essentials",
        price: 2800,
        oldPrice: 5600,
        status: "approved",
        category: "Programming",
        detailsCourse: "NoSQL database concepts, CRUD, and aggregation.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },

    {
        name: "Emma Wilson",
        email: "emma@mail.com",
        title: "UI/UX Design Fundamentals",
        price: 2800,
        oldPrice: 5600,
        status: "approved",
        category: "Design",
        detailsCourse: "Design principles, wireframes, and usability testing.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Emma Wilson",
        email: "emma@mail.com",
        title: "Figma for Beginners",
        price: 2600,
        oldPrice: 5200,
        status: "approved",
        category: "Design",
        detailsCourse: "Design interfaces and prototypes using Figma.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "David Kim",
        email: "david@mail.com",
        title: "Photoshop Essentials",
        price: 2500,
        oldPrice: 5000,
        status: "approved",
        category: "Design",
        detailsCourse: "Photo editing, retouching, and design basics.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },

    {
        name: "Robert Brown",
        email: "robert@mail.com",
        title: "Digital Marketing Basics",
        price: 3000,
        oldPrice: 6000,
        status: "approved",
        category: "Business",
        detailsCourse: "SEO, social media, and online advertising strategies.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Robert Brown",
        email: "robert@mail.com",
        title: "Facebook Ads Mastery",
        price: 3200,
        oldPrice: 6400,
        status: "approved",
        category: "Business",
        detailsCourse: "Create, manage, and optimize Facebook ad campaigns.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },

    {
        name: "Lisa Ray",
        email: "lisa@mail.com",
        title: "Python for Beginners",
        price: 2900,
        oldPrice: 5800,
        status: "approved",
        category: "Programming",
        detailsCourse: "Learn Python syntax, logic, and basic projects.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Lisa Ray",
        email: "lisa@mail.com",
        title: "Data Analysis with Python",
        price: 3500,
        oldPrice: 7000,
        status: "approved",
        category: "Programming",
        detailsCourse: "Use pandas, numpy, and matplotlib for data analysis.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Tom Hardy",
        email: "tom@mail.com",
        title: "Public Speaking",
        price: 2200,
        oldPrice: 4400,
        status: "approved",
        category: "Personal Development",
        detailsCourse: "Build confidence and speak effectively in public.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    },
    {
        name: "Tom Hardy",
        email: "tom@mail.com",
        title: "Time Management",
        price: 2100,
        oldPrice: 4200,
        status: "approved",
        category: "Personal Development",
        detailsCourse: "Increase productivity with proven time management methods.",
        coverPicture: "https://i.ytimg.com/vi/3yO_FR8yiQk/maxresdefault.jpg",
        videoUrl: "https://res.cloudinary.com/dt2hgwxub/video/upload/v1729706148/LearnUp/course-video/video_1729706140713.mp4",
    }
];

module.exports = fakecourses;